/*
 * @Author: JHC521PJJ 
 * @Date: 2023-07-24 22:06:19 
 * @Last Modified by: JHC521PJJ
 * @Last Modified time: 2023-07-24 22:08:20
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * The open source cnpy library is used to convert npy files generated by model training into std::vector
 */

#ifndef __NPY_VEC_H__
#define __NPY_VEC_H__

#include "cnpy.h"
#include <vector>

/*
struct NpyArray {
    std::vector<size_t> shape;
    size_t word_size;
    template<typename T> T* data();
};
*/

inline std::vector<float> npyToVector(const char* npy_path) {
    cnpy::NpyArray npy_arr = cnpy::npy_load(npy_path);    
    return std::vector<float>(npy_arr.data<float>(), npy_arr.data<float>() + npy_arr.shape[1]);
}

inline float npyToValue(const char* npy_path) {
    cnpy::NpyArray npy_value = cnpy::npy_load(npy_path);
    return *npy_value.data<float>();
}

#endif
